version: '3.4'

services:
  docker.manager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "7001:7001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
